name: build
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - run: just check

  docker:
    if: github.ref_name == 'main'
    needs: check
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
      - run: just docker-push latest
      - run: just docker-push "${{ github.workflow }}-${{ github.run_number }}"
