name: build
on: push
jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - run: just check

  build:
    if: github.ref_name == 'main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --release --bin ferrysched_scraper
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: target/release/ferrysched_scraper
