name: scrape
on:
  schedule:
    - cron: '44 2 * * *'
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      S3_BUCKET:
        required: true
      CLOUDFRONT_DISTRIBUTION_ID:
        required: true
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          branch: main
          workflow_conclusion: success
          check_artifacts: true
      - run: chmod a+x release/ferrysched_scraper
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: just upload-data-with-bin release/ferrysched_scraper
