name: scrape

on:
  schedule:
    - cron: '44 11,23 * * *'
  repository_dispatch:
    types: [scrape]
  workflow_dispatch:

jobs:

  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.40.0
      - uses: dawidd6/action-download-artifact@v9
        with:
          workflow: build.yaml
          branch: main
      - run: chmod a+x release/ferrysched_scraper
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: just upload-data-with-bin release/ferrysched_scraper
